### ISSUE TITLE
vizualizer fails with non-existing wikidata link

### ISSUE THREAD

**Issue by Marketa-Lopatkova** [ufal/UMRGraphViz#7]
There might be a non-existing link to wikidata in the processed data (we are sure that there should be a wikilink for some NE but we have not find it - we decided to use "Q0"). However, the vizualizer then fails. 
It would be nice if it can just skip the link (possibly with warning) and proceed.

**Comment by michnov** [comment]
It seems to me that it is exactly what it has been doing. If an entity ID for which a Wiki Data record does not exist is encountered, its name that could not be retrieved is replaced with the "unk" string and a warning is printed to the error console output. I have just only rephrased the message so that it does not start with the word "Error" to not appear so fatal (fb56b19).
I have tried replacing the entity ID in the 3rd sentence in your "Estonsko" file: "Q191" -> "Q0". It results only in the following warning message
```
2024-02-12 17:31:08,198: INFO: processing issue7.txt
2024-02-12 17:31:11,298: WARNING: Failed in retrieving data from WikiData for the id=Q0: id does not exist
```
and the visualization displays it correctly and continues with the following sentences:
![image](https://github.com/ufal/UMRGraphViz/assets/11574860/23b4ca0c-7909-4b45-8436-19085e62ed24)
